version: "3.0"
services:
  web:
    image: bonsik/codebox-project-images:1.0
    container_name: codebox
    ports:
      - 8888:8888

  redis:
    image: redis:alpine
    container_name: redis_boot
    command: redis-server --port 6379
    hostname: redis
    ports:
      - 6379:6379