server:
  port: 8888

---
spring:
  banner:
    location: banner-local.txt

---
spring:
  #스프링 부트 메시지 설정 추가
  #  messages:
  #    basename: errors, messages

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ams_sideproject?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        #use_sql_comments: true
        default_batch_fetch_sizee: 100

  # swagger 오류
  # : Spring boot 2.6버전 이후에 spring.mvc.pathmatch.matching-strategy 값이
  #   ant_apth_matcher에서 path_pattern_parser로 변경되면서 몇몇 라이브러리에서 오류가 발생하고 있다!
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


  mail:
    #Naver smtp server 사용
    #    host: smtp.naver.com
    #    port: 465
    #    username: rnqhstlr2297
    #    password: rnqhstlr2297!
    #    properties:
    #      mail:
    #        smtp:
    #          starttls:
    #            enable: true
    #          auth: true
    #          ssl:
    #            trust: smtp.naver.com
    #            enable: true #반드시 필요 -> naver 에 설정되어있으면

    # Google smtp server 사용
    host: smtp.gmail.com
    port: 587
    username: rnqhstlr2297@gmail.com
    password: ritbhiqxyounajye
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

  #Redis Cache
  redis:
    host: 127.0.0.1
    port: 6379

---
jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK

