server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #AWS RDS IP 주소
    url: jdbc:mysql://ams-sideproject.cplvn3gq33xj.ap-northeast-2.rds.amazonaws.com:3306/ams_sideproject?serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: rnqhstlr123!

  jpa:
    hibernate:
      ddl-auto: create

  properties:
    hibernate:
      show_sql: true
      default_batch_fetch_size: 100

  # swagger 오류
  # : Spring boot 2.6버전 이후에 spring.mvc.pathmatch.matching-strategy 값이
  #   ant_apth_matcher에서 path_pattern_parser로 변경되면서 몇몇 라이브러리에서 오류가 발생하고 있다!
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

    # Naver smtp server 사용
  mail:
    host: smtp.naver.com
    port: 465
    username: rnqhstlr2297
    password: rnqhstlr123!
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          ssl:
            trust: smtp.naver.com
            enable: true #반드시 필요 -> naver 에 설정되어있으면